export const themeStyles = {
  classic: {
    background: 'bg-white',
    heroOverlay: 'bg-black bg-opacity-40',
    heroText: 'text-white',
    headerBackground: 'bg-gray-100',
    headerText: 'text-gray-900',
    subtitleText: 'text-gray-600',
    mainBody: 'bg-white',
    mainText: 'text-gray-800',
    paragraphBackground: 'bg-gray-50',
    paragraphTitle: 'text-gray-900',
    paragraphText: 'text-gray-700',
  },
  mournful: {
    background: 'bg-gray-900',
    heroOverlay: 'bg-black bg-opacity-60',
    heroText: 'text-gray-300',
    headerBackground: 'bg-gray-800',
    headerText: 'text-gray-300',
    subtitleText: 'text-gray-400',
    mainBody: 'bg-gray-900',
    mainText: 'text-gray-300',
    paragraphBackground: 'bg-gray-800',
    paragraphTitle: 'text-gray-300',
    paragraphText: 'text-gray-400',
  },
  positive: {
    background: 'bg-blue-50',
    heroOverlay: 'bg-blue-900 bg-opacity-30',
    heroText: 'text-white',
    headerBackground: 'bg-white',
    headerText: 'text-blue-600',
    subtitleText: 'text-blue-500',
    mainBody: 'bg-blue-50',
    mainText: 'text-blue-900',
    paragraphBackground: 'bg-white',
    paragraphTitle: 'text-blue-600',
    paragraphText: 'text-blue-900',
  },
  modern: {
    background: 'bg-zinc-100',
    heroOverlay: 'bg-zinc-900 bg-opacity-50',
    heroText: 'text-white',
    headerBackground: 'bg-white',
    headerText: 'text-zinc-900',
    subtitleText: 'text-zinc-600',
    mainBody: 'bg-zinc-100',
    mainText: 'text-zinc-800',
    paragraphBackground: 'bg-white',
    paragraphTitle: 'text-zinc-900',
    paragraphText: 'text-zinc-700',
  },
  natural: {
    background: 'bg-stone-50',
    heroOverlay: 'bg-stone-900 bg-opacity-40',
    heroText: 'text-stone-50',
    headerBackground: 'bg-stone-100',
    headerText: 'text-stone-800',
    subtitleText: 'text-stone-600',
    mainBody: 'bg-stone-50',
    mainText: 'text-stone-700',
    paragraphBackground: 'bg-stone-100',
    paragraphTitle: 'text-stone-800',
    paragraphText: 'text-stone-700',
  },
  pastel: {
    background: 'bg-rose-50',
    heroOverlay: 'bg-rose-200 bg-opacity-40',
    heroText: 'text-rose-900',
    headerBackground: 'bg-rose-100',
    headerText: 'text-rose-700',
    subtitleText: 'text-rose-500',
    mainBody: 'bg-rose-50',
    mainText: 'text-rose-800',
    paragraphBackground: 'bg-rose-100',
    paragraphTitle: 'text-rose-700',
    paragraphText: 'text-rose-800',
  },
  vanGogh: {
    background: 'bg-yellow-50',
    heroOverlay: 'bg-indigo-900 bg-opacity-40',
    heroText: 'text-yellow-100',
    headerBackground: 'bg-yellow-100',
    headerText: 'text-indigo-900',
    subtitleText: 'text-indigo-700',
    mainBody: 'bg-yellow-50',
    mainText: 'text-indigo-900',
    paragraphBackground: 'bg-yellow-100',
    paragraphTitle: 'text-indigo-900',
    paragraphText: 'text-indigo-800',
  },
  roman: {
    background: 'bg-red-900',
    heroOverlay: 'bg-red-950 bg-opacity-50',
    heroText: 'text-yellow-100',
    headerBackground: 'bg-red-800',
    headerText: 'text-yellow-100',
    subtitleText: 'text-yellow-200',
    mainBody: 'bg-red-900',
    mainText: 'text-yellow-100',
    paragraphBackground: 'bg-red-800',
    paragraphTitle: 'text-yellow-100',
    paragraphText: 'text-yellow-200',
  },
  australian: {
    background: 'bg-orange-100',
    heroOverlay: 'bg-orange-900 bg-opacity-40',
    heroText: 'text-orange-50',
    headerBackground: 'bg-orange-200',
    headerText: 'text-orange-900',
    subtitleText: 'text-orange-700',
    mainBody: 'bg-orange-100',
    mainText: 'text-orange-900',
    paragraphBackground: 'bg-orange-200',
    paragraphTitle: 'text-orange-900',
    paragraphText: 'text-orange-800',
  },
};