export const themeStyles = {
  classic: {
    background: 'bg-white',
    heroOverlay: 'bg-black bg-opacity-40',
    heroText: 'text-white',
    headerBackground: 'bg-gray-100',
    headerText: 'text-gray-900',
    subtitleText: 'text-gray-600',
    mainBody: 'bg-white',
    mainText: 'text-gray-800',
    paragraphBackground: 'bg-gray-50',
    paragraphTitle: 'text-gray-900',
    paragraphText: 'text-gray-700',
  },
  mournful: {
    background: 'bg-gray-900',
    heroOverlay: 'bg-black bg-opacity-60',
    heroText: 'text-gray-300',
    headerBackground: 'bg-gray-800',
    headerText: 'text-gray-300',
    subtitleText: 'text-gray-400',
    mainBody: 'bg-gray-900',
    mainText: 'text-gray-300',
    paragraphBackground: 'bg-gray-800',
    paragraphTitle: 'text-gray-300',
    paragraphText: 'text-gray-400',
  },
  positive: {
    background: 'bg-blue-50',
    heroOverlay: 'bg-blue-900 bg-opacity-30',
    heroText: 'text-white',
    headerBackground: 'bg-white',
    headerText: 'text-blue-600',
    subtitleText: 'text-blue-500',
    mainBody: 'bg-blue-50',
    mainText: 'text-blue-900',
    paragraphBackground: 'bg-white',
    paragraphTitle: 'text-blue-600',
    paragraphText: 'text-blue-900',
  },
}; 